spring:
  config:
    activate:
      on-profile: local-mariadb
  datasource:
    url: jdbc:mariadb://localhost:3306/lachelein_db
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PWD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true