spring:
  # MySQL Datasource 설정
  datasource:
    mysql:
      url: jdbc:mysql://127.0.0.1:3306/testdb
      username: ${LOCAL_DB_USERNAME}
      password: ${LOCAL_DB_PWD}
      driver-class-name: com.mysql.cj.jdbc.Driver
    mariadb:
      url: jdbc:mariadb://localhost:3306/mariadb_db
      driver-class-name: org.mariadb.jdbc.Driver
      username: ${MARIADB_USER}
      password: ${MARIADB_PASSWORD}

  # JPA (Java Persistence API) 설정
  jpa:
    hibernate:
      ddl-auto: update # 애플리케이션 실행 시 엔티티에 맞춰 테이블 자동 변경/생성
    show-sql: true # 실행되는 SQL 쿼리를 로그로 보여줌
    properties:
      hibernate:
        format_sql: true # SQL 로그를 보기 좋게 포맷팅